import Head from "next/head";
import Appnavbar from "./Appnavbar";
import BreakingNews from "./BreakingNews";
import PoliticsSection from "./PoliticsSection";
import Blog from "./Blog";
import GoogleAds from "./GoogleAds";
import EnvironmentalProtectionRevolution from "./EnvironmentalProtectionRevolution";
import SocailAds from "./SocailAds";
import Footer from "./Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Candorium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://site-assets.fontawesome.com/releases/v6.0.0/css/all.css" rel="stylesheet" />
      </Head>
       <Appnavbar/>
       <BreakingNews/>
       <PoliticsSection/>
       <GoogleAds/>
       <Blog/>
       <EnvironmentalProtectionRevolution/>
       <SocailAds/>
       <Footer/>
    </>
  );
}
